import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service | DraftPilot',
  description: 'Terms of Service governing the use of DraftPilot Chrome extension and web application, including AI disclaimers and human-in-the-loop policies.',
};

export default function TermsOfServicePage() {
  return (
    <div className="py-16 md:py-24 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Top Header / Breadcrumb */}
        <div className="mb-8">
          <Link 
            href="/" 
            className="inline-flex items-center gap-1.5 text-xs text-text-dim hover:text-accent-light transition-colors mb-4"
          >
            <span>← Back to Home</span>
          </Link>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/30 text-accent-light text-xs font-semibold uppercase tracking-wider mb-3">
            <span>Legal &amp; Privacy</span>
          </div>
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight text-text mb-4">
            Terms of Service
          </h1>
          <p className="text-sm text-text-dim">
            <strong>Last Updated:</strong> September 2026 • <strong>Version:</strong> 2.0
          </p>
        </div>

        {/* Important Callout Box: Human-in-the-Loop */}
        <div className="p-6 md:p-8 rounded-3xl bg-accent/5 border border-accent/30 shadow-xl mb-12 space-y-3">
          <div className="flex items-center gap-2 text-accent-light font-bold text-sm uppercase tracking-wide">
            <span>⚠️</span>
            <span>Important Notice: Human-in-the-Loop Requirement</span>
          </div>
          <p className="text-xs text-text-muted leading-relaxed">
            DraftPilot is an AI-assisted co-pilot designed to suggest draft replies. <strong className="text-text">You and your support agents retain sole and ultimate responsibility for reviewing, modifying, verifying, and sending any message generated by DraftPilot.</strong> DraftPilot does not automatically dispatch emails without human intervention. We explicitly disclaim liability for any unreviewed or erroneous statements sent by your agents.
          </p>
        </div>

        {/* Content Sections */}
        <div className="space-y-10 text-sm text-text-muted leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">1. Acceptance of Terms</h2>
            <p>
              By installing the DraftPilot Chrome Extension, accessing our web application, or creating an account, you (&ldquo;User,&rdquo; &ldquo;Customer,&rdquo; or &ldquo;You&rdquo;) agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you are agreeing to these Terms on behalf of an organization or company, you represent and warrant that you have the authority to bind that entity. If you do not agree to these Terms, you must not use our software or services.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">2. Description of Services</h2>
            <p>
              DraftPilot provides software tools that streamline customer support correspondence. The service consists of:
            </p>
            <ul className="list-disc pl-5 space-y-2">
              <li>A Chrome Manifest V3 browser extension that interfaces with Gmail (`mail.google.com`) to detect open email threads, apply client-side PII scrubbing, and insert draft replies.</li>
              <li>A web dashboard for managing team workspaces, custom canned macros, knowledge base documentation, seat allocations, and billing settings.</li>
              <li>An AI inference orchestration engine that grounds draft generations in your team&apos;s configured macros and knowledge documentation.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">3. Human-in-the-Loop &amp; AI Accuracy Disclaimer</h2>
            <div className="p-4 rounded-2xl bg-elevated border border-border/70 space-y-2 text-xs">
              <p className="font-semibold text-text">3.1 Agent Review Obligation</p>
              <p>
                DraftPilot is designed strictly as an assistive tool (&ldquo;co-pilot&rdquo;). All drafted responses require human inspection and deliberate insertion before being sent. You agree that your team members will review every generated draft for factual accuracy, appropriateness, legal compliance, and tone before sending.
              </p>
              <p className="font-semibold text-text mt-3">3.2 Disclaimer of AI Warranties</p>
              <p>
                Artificial intelligence models, including large language models, can produce incorrect, incomplete, hallucinatory, or offensive content. DRAFTPILOT MAKES NO WARRANTIES OR REPRESENTATIONS THAT AI DRAFTS WILL BE 100% ACCURATE, UNINTERRUPTED, OR FREE OF ERRORS. DRAFTPILOT SHALL NOT BE RESPONSIBLE OR LIABLE FOR ANY COMMITMENTS, REFUND PROMISES, OR CONTRACTUAL OBLIGATIONS CREATED AS A RESULT OF AN AGENT SENDING AN UNVERIFIED DRAFT.
              </p>
            </div>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">4. Accounts &amp; Team Workspaces</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-text">Account Security:</strong> You are responsible for safeguarding your login credentials and for all activities that occur under your workspace. Notify us immediately of any unauthorized access.</li>
              <li><strong className="text-text">Seat Licensing:</strong> Accounts on our Team Co-Pilot plan are licensed per active agent seat. Sharing individual login credentials across multiple agents to circumvent seat limits is strictly prohibited.</li>
              <li><strong className="text-text">Workspace Administration:</strong> Workspace owners have administrative authority over team macros, seat assignments, and billing configurations.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">5. Subscriptions, Fees &amp; Billing</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-text">Free Starter Tier:</strong> Includes up to 50 AI drafts per month for 1 user seat with standard PII scrubbing.</li>
              <li><strong className="text-text">Team Co-Pilot Tier:</strong> Billed at $19 per agent per month (or $15 per agent per month billed annually). Includes 1,000 AI drafts per agent per month and unlimited shared team macros.</li>
              <li><strong className="text-text">14-Day Free Trial:</strong> Team tiers may offer a 14-day free trial. If not cancelled before the trial ends, your card will be charged for the selected billing cadence.</li>
              <li><strong className="text-text">Cancellations &amp; Refunds:</strong> You can cancel your subscription at any time via the billing portal. Cancellations take effect at the end of the current billing cycle. Payments are non-refundable except where required by law.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">6. Acceptable Use Policy</h2>
            <p>You agree not to use DraftPilot to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Generate or distribute unsolicited bulk communications, spam, or phishing campaigns.</li>
              <li>Impersonate individuals or organizations deceptively.</li>
              <li>Transmit, store, or generate defamatory, fraudulent, infringing, or illegal material.</li>
              <li>Reverse engineer, decompile, or attempt to extract the source code of our backend services or proprietary algorithms.</li>
              <li>Circumvent or tamper with rate limits, quota counters, or BotID protection mechanisms.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">7. Intellectual Property &amp; Customer Data</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong className="text-text">Customer Ownership:</strong> You retain all right, title, and interest in and to your data, including your customer emails, custom macros, knowledge base documents, and sent messages.</li>
              <li><strong className="text-text">DraftPilot IP:</strong> DraftPilot, its logos, software, website, extension, and documentation are the exclusive intellectual property of DraftPilot.</li>
              <li><strong className="text-text">No Model Training:</strong> We do not acquire any ownership in your data and do not use your proprietary macros or communications to train third-party machine learning models.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">8. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DRAFTPILOT, ITS DIRECTORS, EMPLOYEES, OR PARTNERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING LOSS OF PROFITS, DATA, USE, GOODWILL, OR BUSINESS REPUTATION) ARISING OUT OF OR IN CONNECTION WITH YOUR ACCESS TO OR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
            <p>
              OUR TOTAL AGGREGATE LIABILITY UNDER THESE TERMS SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO DRAFTPILOT DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">9. Modifications to Terms</h2>
            <p>
              We reserve the right to revise or update these Terms at any time. If a revision is material, we will provide at least 15 days&apos; notice via email or within the web dashboard before new terms take effect. Continued use of the service following such modifications constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">10. Governing Law &amp; Dispute Resolution</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which DraftPilot operates, without regard to its conflict of law provisions. Any dispute arising from these Terms shall be resolved through good-faith mutual negotiation, or if unresolved, through binding individual arbitration.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-text">11. Contact Information</h2>
            <p>
              For legal notices, terms inquiries, or enterprise agreement questions, please contact:
            </p>
            <div className="p-4 rounded-2xl bg-elevated border border-border text-xs space-y-1">
              <p className="text-text font-semibold">DraftPilot Legal &amp; Compliance</p>
              <p>Email: <a href="mailto:legal@draftpilot.app" className="text-accent-light">legal@draftpilot.app</a></p>
              <p>Support: <a href="mailto:support@draftpilot.app" className="text-accent-light">support@draftpilot.app</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
